# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# db/seed.rb

puts "Seeding types..."

types = [
    {name: 'Planta', color: '#9BBB31'},
    {name: 'Fogo', color: '#F2673C'},
    {name: 'Voador', color: '#79B1B5'},
    {name: 'Normal', color: '#A6A6A6'},
    {name: 'Psíquico', color: '#CB67D0'},
    {name: 'Lutador', color: '#868278'},
    {name: 'Elétrico', color: '#DCB747'},
    {name: 'Água', color: '#4592C4'},
    {name: 'Terra', color: '#A4633F'},
    {name: 'Inseto', color: '#94B34F'},
    {name: 'Aço', color: '#9EB7B8'},
    {name: 'Pedra', color: '#5F5E5B'},
    {name: 'Fada', color: '#E584A1'},
    {name: 'Som', color: '#8B7C56'},
    {name: 'Sombrio', color: '#2F2F87'},
    {name: 'Fantasma', color: '#624F8A'},
    {name: 'Sintético', color: '#908FA2'},
    {name: 'Cósmico', color: '#A686D9'},
    {name: 'Indefinido', color: '#333333'},
    {name: 'Dragão', color: '#B84651'},
    {name: 'Gelo', color: '#B4CBD9'},
    {name: 'Venenoso', color: '#57D96F'}
]

types.each do |creatingTypes|
Type.find_or_create_by(creatingTypes)

end
puts "Seeding types done."

puts "Seeding bagmons..."

def seed_image(number)
    "seed/#{number}.png"
end

bagmonlist = [
    {number: "001", name: "Voara", type_id: 1},
    {number: "002", name: "Azurara", type_id: 1},
    {number: "003", name: "Ararazul", type_id: 1},
    {number: "004", name: "Pequemico", type_id: 2},
    {number: "005", name: "Micorado", type_id: 2},
    {number: "006", name: "Douraleão", type_id: 2},
    {number: "007", name: "Capi", type_id: 8},
    {number: "008", name: "Varacapi", type_id: 8},
    {number: "009", name: "Capilorde", type_id: 8},
    {number: "010", name: "Tamanduí", type_id: 9},
    {number: "011", name: "Tamirim", type_id: 9},
    {number: "012", name: "Lutanduá", type_id: 9},
    {number: "013", name: "Caralata", type_id: 4},
    {number: "014", name: "Caramelo", type_id: 4},
    {number: "015", name: "Viramelo", type_id: 4},
    {number: "016", name: "Iaçá", type_id: 1},
    {number: "017", name: "Açaíne", type_id: 1},
    {number: "018", name: "Naná", type_id: 1},
    {number: "019", name: "Guaranin", type_id: 1},
    {number: "020", name: "Beboto", type_id: 8},
    {number: "021", name: "Bodutor", type_id: 8},
    {number: "022", name: "Laguito", type_id: 10},
    {number: "023", name: "Durito", type_id: 10},
    {number: "024", name: "Bansquito", type_id: 10},
    {number: "025", name: "Chanin", type_id: 4},
    {number: "026", name: "Fofilho", type_id: 1},
    {number: "027", name: "Slicurau", type_id: 1},
    {number: "028", name: "Pamonhana", type_id: 1},
    {number: "029", name: "Jondi", type_id: 9},
    {number: "030", name: "Bojarro", type_id: 9},
    {number: "031", name: "Benja", type_id: 17},
    {number: "032", name: "Benjamais", type_id: 17},
    {number: "033", name: "Benjamuitos", type_id: 17},
    {number: "034", name: "Pondi", type_id: 13},
    {number: "035", name: "Diquejos", type_id: 13},
    {number: "036", name: "Besarela", type_id: 10},
    {number: "037", name: "Besercules", type_id: 10},
    {number: "038", name: "Julicac", type_id: 1},
    {number: "039", name: "Caquilete", type_id: 1},
    {number: "040", name: "Grafé", type_id: 1},
    {number: "041", name: "Torrafé", type_id: 1},
    {number: "042", name: "Cafasma", type_id: 1},
    {number: "043", name: "Duratista", type_id: 12},
    {number: "044", name: "Dutrino", type_id: 12},
    {number: "045", name: "Duraíba", type_id: 12},
    {number: "046", name: "Zégoti", type_id: 13},
    {number: "047", name: "Pfizegator", type_id: 8},
    {number: "048", name: "Jacarevac", type_id: 8},
    {number: "049", name: "Astracaré", type_id: 8},
    {number: "050", name: "Colote", type_id: 17},
    {number: "051", name: "Cajaça", type_id: 17},
    {number: "052", name: "Véiguerrero", type_id: 17},
    {number: "053", name: "Biscolacha", type_id: 4},
    {number: "054", name: "Bolachoito", type_id: 4},
    {number: "055", name: "Ratinrrato", type_id: 7},
    {number: "056", name: "Ratobum", type_id: 7},
    {number: "057", name: "Cuscute", type_id: 1},
    {number: "058", name: "Monstruz", type_id: 1},
    {number: "059", name: "Querokero", type_id: 3},
    {number: "060", name: "Querocaos", type_id: 3},
    {number: "061", name: "Bemtevi", type_id: 3},
    {number: "062", name: "Bemteverei", type_id: 3},
    {number: "063", name: "Bemtevejo", type_id: 3},
    {number: "064", name: "Pregaiana", type_id: 16},
    {number: "065", name: "Largata", type_id: 10},
    {number: "066", name: "Casuleta", type_id: 10},
    {number: "067", name: "Borboleto", type_id: 10},
    {number: "068", name: "Brabuleta", type_id: 10},
    {number: "069", name: "Uvisier", type_id: 1},
    {number: "070", name: "Sansoelho", type_id: 13},
    {number: "071", name: "Coxita", type_id: 13},
    {number: "072", name: "Pasfeira", type_id: 13},
    {number: "073", name: "Caldicana", type_id: 16},
    {number: "074", name: "Pequetixa", type_id: 20},
    {number: "075", name: "Calanqui", type_id: 20},
    {number: "076", name: "Peteiú", type_id: 20},
    {number: "077", name: "Bezeta", type_id: 4},
    {number: "078", name: "Carapreta", type_id: 4},
    {number: "079", name: "Bezela", type_id: 4},
    {number: "080", name: "Vacarela", type_id: 4},
    {number: "081", name: "Capritidos", type_id: 4},
    {number: "082", name: "Sapoeira", type_id: 6},
    {number: "083", name: "Jiusapo", type_id: 6},
    {number: "084", name: "Capagaz", type_id: 16},
    {number: "085", name: "Carcego", type_id: 3},
    {number: "086", name: "Morganca", type_id: 3},
    {number: "087", name: "Bebolvo", type_id: 8},
    {number: "088", name: "Octeddy", type_id: 8},
    {number: "089", name: "Tazum", type_id: 17},
    {number: "090", name: "Montazo", type_id: 17},
    {number: "091", name: "Fantazo", type_id: 17},
    {number: "092", name: "Feijote", type_id: 16},
    {number: "093", name: "Banloira", type_id: 16},
    {number: "094", name: "Mamuna", type_id: 1},
    {number: "095", name: "Mantrio", type_id: 1},
    {number: "096", name: "Massinas", type_id: 1},
    {number: "097", name: "Jubará", type_id: 4},
    {number: "098", name: "Josoré", type_id: 4},
    {number: "099", name: "Fixuxo", type_id: 4},
    {number: "100", name: "Txucão", type_id: 4},
    {number: "101", name: "Chifíbio", type_id: 1},
    {number: "102", name: "Saparrão", type_id: 1},
    {number: "103", name: "Chimarrã", type_id: 1},
    {number: "104", name: "Terereca", type_id: 1},
    {number: "105", name: "Sin", type_id: 5},
    {number: "106", name: "Salabin", type_id: 5},
    {number: "107", name: "Ziriguidum", type_id: 5},
    {number: "108", name: "Elecbol", type_id: 17},
    {number: "109", name: "Brazorb", type_id: 17},
    {number: "110", name: "Doncorvo", type_id: 8},
    {number: "111", name: "Canarin", type_id: 4},
    {number: "112", name: "Pistolin", type_id: 6},
    {number: "113", name: "Tatuleco", type_id: 9},
    {number: "114", name: "Tatunastra", type_id: 9},
    {number: "115", name: "Tupin", type_id: 3},
    {number: "116", name: "Volpiniquin", type_id: 3},
    {number: "117", name: "Floriniquin", type_id: 3},
    {number: "118", name: "Hidroniquin", type_id: 3},
    {number: "119", name: "Brasaniquin", type_id: 3},
    {number: "120", name: "Titaniquin", type_id: 3},
    {number: "121", name: "Urumengo", type_id: 3},
    {number: "122", name: "Cebrutius", type_id: 17},
    {number: "123", name: "Diguidim", type_id: 17},
    {number: "124", name: "Orcantos", type_id: 8},
    {number: "125", name: "Pormeiras", type_id: 1},
    {number: "126", name: "Santaulo", type_id: 5},
    {number: "127", name: "Mosquião", type_id: 3},
    {number: "128", name: "Peixuanã", type_id: 8},
    {number: "129", name: "Pirarupeixe", type_id: 8},
    {number: "130", name: "Imperátilus", type_id: 20},
    {number: "131", name: "Irritator", type_id: 12},
    {number: "132", name: "Celeconda", type_id: 1},
    {number: "133", name: "Suculeste", type_id: 1},
    {number: "134", name: "Ursocotom", type_id: 4},
    {number: "135", name: "Araupinha", type_id: 1},
    {number: "136", name: "Araubroto", type_id: 1},
    {number: "137", name: "Arauforte", type_id: 1},
    {number: "138", name: "Xunave", type_id: 18},
    {number: "139", name: "Cristaluna", type_id: 18},
    {number: "140", name: "Sereiara", type_id: 8},
    {number: "141", name: "Piropira", type_id: 1},
    {number: "142", name: "Sacerê", type_id: 3},
    {number: "143", name: "Cobratá", type_id: 2},
    {number: "144", name: "Mulantã", type_id: 2},
    {number: "145", name: "Mapinguá", type_id: 6},
    {number: "146", name: "Loguará", type_id: 9},
    {number: "147", name: "Iaguará", type_id: 11},
    {number: "148", name: "Velopya", type_id: 3},
    {number: "149", name: "Gambiarros", type_id: 17},
    {number: "150", name: "Bilu", type_id: 18},
    {number: "151", name: "Bivaldo", type_id: 18},
]
  
bagmonlist.each do |attributes|
    puts "Bringing life to #{attributes[:name]}";
    attributes[:image] = seed_image(attributes[:number])
    Bagmon.find_or_create_by(attributes)
end

puts "Seeding bagmons done."


